config/routes.rb
Rails.application.routes.draw do
  resources :groups do
    resources :payments
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    return unless user.present? # additional permissions for logged in users (they can manage their posts)

    can :manage, Group, user_id: user.id
    can :manage, Payment, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user, foreign_key: :user_id
  has_and_belongs_to_many :payments, through: :payments_groups

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user, foreign_key: :user_id
  has_and_belongs_to_many :groups, through: :payments_groups

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups, dependent: :destroy, foreign_key: :user_id
  has_many :payments, dependent: :destroy, foreign_key: :user_id

  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end

  def after_sign_in_path_for(_resource)
    groups_path
  end

  def after_sign_out_path_for(_resource)
    root_path
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, alert: exception.message
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  # GET /groups or /groups.json
  def index
    @groups = Group.all.where(user: current_user).includes(:payments)
  end

  # GET /groups/1 or /groups/1.json
  def show
    @groups = Group.find_by(id: params[:id])
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # POST /groups or /groups.json
  def create
    unless current_user.present?
      flash[:alert] = 'You must be logged in to create a group'
      redirect_to new_user_session_path
      return
    end
    @group = Group.new(group_params.merge(user: current_user))

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_url, notice: 'Group was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!

  # GET /payments or /payments.json
  def index
    @payments = Group.find(params[:group_id]).payments.includes(:user).order(created_at: :desc)
    @category_id = params[:group_id]
  end

  # GET /payments/new
  def new
    @payment = Payment.new
    group_ids = Group.select('groups.name').where(user: current_user).pluck(:id)
    @groups = Group.where(id: group_ids)
    @group_id = params[:group_id]
  end

  # POST /payments or /payments.json
  def create
    @payment = current_user.payments.build(payment_params)
    @payment.groups << Group.find_by(id: params[:group_id])

    respond_to do |format|
      if @payment.save
        format.html { redirect_to group_path(params[:group_id]), notice: 'Payment was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def payment_params
    params.require(:payment).permit(:name, :amount, :group)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/groups/_form.html.erb
<div class="container mt-5">
<%= bootstrap_form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>
      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.text_field :icon %>
  </div>

  <div>
    <%= form.submit 'Create Category', :class=>"btn btn-primary w-100" %>
  </div>
<% end %>
</div>

app/views/groups/_navbar.html.erb
<nav class="navbar bg-primary p-4 w-100">
  <p class="signup_name"><%= current_user.name.capitalize %></p>
  <h5>TRANSACTIONS</h5>
  <%= button_to "Log out", destroy_user_session_path, :class => 'btn log-out', :method => :delete, data: {turbo: false}%>
</nav>

app/views/groups/index.html.erb
<%= render partial: "navbar" %>
<div id="groups">
  <% @groups.each do |group| %>
    <ul class="group--section">
    <li class= "single__group__item">
    <%= link_to group_path(group.id), class: "single__group__item__link" do %>
    <div class="group__container">
      <div class="group__items">
        <div class="group__properties">
          <div class="group__details">
          <div class="group__icon">
          <img class="category-image" src="<%= group.icon %>" alt="Group Icon" width="120" height="150">
         </div>
            <h4><%= group.name %></h4>
            <p>$<%= group.payments.sum(:amount)%></p>
          </div>
          <div class="group__utilities">
            <h6>Created at: <span><%= group.created_at.strftime("%d %B, %Y") %></span></h6>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    </li>
  </ul>
  <% end %>
</div>
<div class="fixed-bottom add__category-btn">
<%= link_to "ADD CATEGORY", new_group_path, class: "btn btn-success text-align-center w-100 p-3" %>
</div>

app/views/groups/new.html.erb
<nav class="navbar bg-primary w-100 p-4">
  <%= link_to groups_path, :class => 'back__icon' do %>
    <i class="fa-sharp fa-solid fa-arrow-left-long"></i>
  <% end %>
  <h5 class="text-center">New Category</h5>
  <%= button_to "Log out", destroy_user_session_path, :class => 'btn', :method => :delete, data: {turbo: false}%>
</nav>

<%= render "form", group: @group %>

app/views/groups/show.html.erb
<nav class="navbar bg-primary w-100 p-4">
  <%= link_to groups_path, :class => 'back__icon' do %>
    <i class="fa-sharp fa-solid fa-arrow-left-long"></i>
  <% end %>
  <h5>DETAILS</h5>
  <% if can? :delete, @groups %>
  <%= button_to "Delete group", @group, method: :delete, :class => 'btn btn-outline-danger' %>
  <% end %>
</nav>

<div class="group__payment__details">
<div class="group__icon" style="padding: 0.5rem">
  <img class=".rounded-circle category-image" src="<%= @groups.icon %>" alt="Group Icon" width="120" height="150">
  <h4><%= @groups.name %></h4>
</div>
<div class="group__payment_summary">
<h5>Balance</h5>
<p>$<%= @groups.payments.sum(:amount) %></p>
</div>
<div class="payments--container">
<% @groups.payments.order(created_at: :desc).each do |payment| %>
  <div class="single__payment">
    <div class="group__properties">
      <h4><%= payment.name %></h4>
        <p>$<%= payment.amount %></p>
        <p><%= payment.created_at.strftime("%d %B, %Y") %></p>
    </div>
  </div>
<% end %>
</div>
<div class="fixed-bottom mb-0">
<%= link_to "ADD NEW PAYMENT", new_group_payment_path(@groups), class: "btn btn-success text-align-center w-100 p-3" %>
</div>
</div>

app/views/home/index.html.erb
<div class="conatiner-fluid home-page">
    <div class="row no-gutter">
        <div class="col-md-12">
            <div class="d-flex align-items-center py-5">
             <div class="container">
              <div class="row">
                <div class="col-12 col-lg-6 mx-auto">
                <div class="postion-relative">
                        <div class="position-absolute top-50 start-50 translate-middle"><h1 class="text-center header-logo">BUDGETLY</h1></div> 
                        <div class="position-absolute bottom-0 start-50 translate-middle-x">
                        <%= link_to "LOG IN", new_user_session_path, class: "btn btn-primary py-2 mb-4 mt-2 fw-bold w-100" %>
                        <%= link_to 'SIGN UP', new_user_registration_path, class: "btn py-2 mb-4 fw-bold w-100" %>
                        </div>
                        </div>
                        </div>
                    </div>
                 </div>
            </div>
        </div>
    </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://kit.fontawesome.com/ecb44d8fff.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container" id="messages">
    <% if flash.notice %>
    <p class="alert alert-primary mt-5" role="alert"><%= notice %></p>
    <% end %>
    <% if flash.alert %>
    <p class="alert alert-danger mt-5" role="alert"><%= alert %></p>
    <% end %>
    </div>
    <%= yield %>
  </body>
  <script>
  $(document).ready(function(){
    setTimeout(function(){
    $('.alert').slideUp();
    }, 5000);
  })
</script>
</html>

app/views/payments/_form.html.erb
<div class="container mt-5">
<%= bootstrap_form_with(model: payment, url: group_payments_path) do |form| %>
  <% if payment.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.collection_select :group_id, @groups, :id, :name %>

  <div>
    <%= form.submit 'Create Payment', :class=>"btn btn-primary w-100" %>
  </div>
<% end %>
</div>

app/views/payments/_payment.html.erb
<div id="<%= dom_id payment %>">
  <p>
    <strong>Name:</strong>
    <%= payment.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= payment.amount %>
  </p>

</div>

app/views/payments/index.html.erb
<% if flash.notice %>
<p class="alert alert-primary mt-5" role="alert"><%= notice %></p>
<% end %>

<h1>Payments</h1>

<div id="payments">
  <% @payments.each do |payment| %>
    <%= render payment %>
  <% end %>
</div>

<%= link_to "New payment", new_group_payment_path %>

app/views/payments/new.html.erb
<nav class="navbar bg-primary w-100 p-4">
  <%= link_to groups_path, :class => 'back__icon' do %>
    <i class="fa-sharp fa-solid fa-arrow-left-long"></i>
  <% end %>
  <h5 class="text-center">New Payment</h5>
  <%= button_to "Log out", destroy_user_session_path, :class => 'btn', :method => :delete, data: {turbo: false}%>
</nav>

<%= render "form", payment: @payment %>

app/views/payments/show.html.erb
<%= render @payment %>

<div>
  <%= link_to "Edit this payment", edit_payment_path(@payment) %> |
  <%= link_to "Back to payments", payments_path %>

  <%= button_to "Destroy this payment", @payment, method: :delete %>
</div>